gemfile: false
verify_signatures: false

PreCommit:
  BundleCheck:
    enabled: true

  EsLint:
    enabled: true
    required_executable: npx
    command: ["npx", "--no-install", "eslint", "-f", "compact", "."]
    exclude:
      - .eslintrc.js

  FixMe:
    enabled: true
    keywords: ["FIXME"]
    exclude:
      - .overcommit.yml

  LocalPathsInGemfile:
    enabled: true

  RailsSchemaUpToDate:
    enabled: true

  RubySyntax:
    enabled: true
    exclude:
      - pg_scaffold/lib/generators/**/templates/**/*

  SlimLint:
    enabled: true
    exclude:
      - pg_scaffold/lib/generators/**/templates/**/*

  RuboCop:
    enabled: true
    required_executable: bundle
    command: ["bundle", "exec", "rubocop"]
    on_warn: fail

  Stylelint:
    enabled: false
    required_executable: npx
    command: ["npx", "--no-install", "stylelint"]
    include:
      - app/assets/**/*.css
      - app/assets/**/*.scss
      - app/components/**/*.css
      - app/components/**/*.scss
      - app/javascript/**/*.css
      - app/javascript/**/*.scss

  TrailingWhitespace:
    enabled: true
    exclude:
      - "**/*.svg"
      - "**/db/structure.sql"
      - "**/*.slim"
      - "vendor/**/*"

  YamlSyntax:
    enabled: true
    exclude:
      - "test/fixtures/**/*.yml"

  YarnCheck:
    enabled: true

# PostCheckout:
#   ALL:
#     quiet: true
