require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

Style/Documentation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  # DisabledByDefault: true
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - '*.gemspec'
    - 'Capfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'spec/dummy/Rakefile'
    - 'spec/dummy/db/**/*'
    - 'spec/dummy/bin/**/*'
    - 'spec/dummy/config/**/*'
    - 'spec/dummy/config.ru'
    - 'spec/dummy/node_modules/**/*'
    - 'spec/dummy/tmp/**/*'
    - 'vendor/**/*'
    - 'scripts/**/*'
    - 'lib/tasks/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - '**/version.rb'
