inherit_from:
  - config/.rubocop.base.yml
  - .rubocop_todo.yml

# AllCops:
#   Exclude:
#     - '**/templates/**/*'
#     - 'spec/dummy/Rakefile'
#     - 'spec/dummy/db/**/*'
#     - 'spec/dummy/bin/**/*'
#     - 'spec/dummy/config/**/*'
#     - 'spec/dummy/config.ru'
#     - 'spec/dummy/node_modules/**/*'
#     - 'spec/dummy/tmp/**/*'
#     - '**/version.rb'

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.4
  Exclude:
    - 'Gemfile'
    - '*.gemspec'
    - 'Capfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - '**/templates/**/*'
    - '**/version.rb'
    - 'pg_engine/lib/tasks/auto_anotar_modelos.rake'
    - 'spec/dummy/Rakefile'
    - 'spec/dummy/db/**/*'
    - 'spec/dummy/bin/**/*'
    - 'spec/dummy/config/**/*'
    - 'spec/dummy/config.ru'
    - 'spec/dummy/node_modules/**/*'
    - 'spec/dummy/tmp/**/*'
    - 'pg_engine/db/**/*'
    - 'pg_engine/config/**/*'
