default: &default
  host: localhost
  port: 5432
  username: pgrails
  password: pgrails
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: 5

development:
  <<: *default
  database: pg_rails_development

test:
  <<: *default
  database: pg_rails_test
