default: &default
  host: localhost
  port: 5432
  username: pg_rails
  password: pg_rails
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: 5

development:
  <<: *default
  database: pg_rails_development

test:
  <<: *default
  database: pg_rails_test
