sidebar:
  -
    name: La Home
    path: root_path
  -
    name: ActiveAdmin
    path: active_admin_root_path
  -
    name: Categorias
    path: admin_categoria_de_cosas_path
  -
    name: Cosas
    path: admin_cosas_path
