sidebar.not_signed_in:
  -
    name: Crear una cuenta
    path: new_user_registration_path
  -
    name: Iniciar sesión
    path: new_user_session_path
  -
    name: Contacto
    path: new_public_mensaje_contacto_path
sidebar.signed_in:
  -
    name: La Home
    path: root_path
  -
    name: Categorias front
    path: users_categoria_de_cosas_path
  -
    name: Cosas front
    path: users_cosas_path
  -
    name: Mi perfil
    path: edit_user_registration_path
    policy: policy(Current.user).edit?
  -
    name: Cerrar sesión
    path: destroy_user_session_path
    attributes: 'data-turbo-method="delete"'
  -
    name: Eventos
    path: admin_eventos_path
  -
    name: Emails
    path: admin_emails_path
  -
    name: Email logs
    path: admin_email_logs_path
  -
    name: Users
    path: admin_users_path
  -
    name: Accounts
    path: admin_accounts_path
  -
    name: User Accounts
    path: admin_user_accounts_path
  -
    name: Categorias
    path: admin_categoria_de_cosas_path
  -
    name: Cosas
    path: admin_cosas_path
# sidebar.developer:
#   -
#     name: ActiveAdmin
#     path: active_admin_root_path
#     policy: "@user.developer?"
#   -
#     name: Users
#     path: admin_users_path
#     policy: "@user.developer?"
#   -
#     name: Tipos Cbtes
#     path: admin_tipo_cbtes_path
#     policy: "@user.developer?"
#   -
#     name: Config. pruebas
#     path: users_setup_configuracion_pruebas_path
#     policy: "@user.developer?"
