sidebar:
  -
    name: La Home
    path: root_path
  -
    name: Personas
    path: admin_personas_path
  -
    name: Categorias
    path: admin_categoria_de_cosas_path
  -
    name: blas
    path: admin_blas_path
  -
    name: ActiveAdmin
    path: active_admin_root_path
